Add `LTE` instruction.
valida-xyz/valida pull request #121
Opened 2024-03-15 19:17 UTC by thealmarty

- closes https://github.com/lita-xyz/llvm-valida/issues/63
- for the STARK, I just added an extra output constraint: the output should be 1 if `is_lte` & `input_1 == input_2`
- now all tests pass when one runs `bash llvm-test-suite/run-valida-tests.sh`

2024-03-16 18:07 UTC, morganthomas requested changes
This should build in CI once you merge `main` into it. This would apply the correct Plonky3 version pin in CI. I was able to build it locally. All the tests passed except for `prove_fibonacci`. This one failed for me like this:

```
failures:

---- prove_fibonacci stdout ----
thread 'prove_fibonacci' panicked at /home/morgan/code/lita/issue/lte/valida/machine/src/quotient.rs:41:35:
attempt to subtract with overflow
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    prove_fibonacci

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.51s
```

Not sure what happened here, but am willing to help to track it down.

2024-03-18 15:05 UTC, thealmarty commented
Thanks Morgan. Now that I rebased I can see the same error you mentioned. Looking into it.

2024-03-18 15:08 UTC, thealmarty commented on alu_u32/src/lt/mod.rs
>              }
`a`, `b`, `c` have local scopes so it seems repetition is necessary unfortunately.

2024-03-18 15:46 UTC, morganthomas commented on alu_u32/src/lt/mod.rs
>              }
Ah, good point.

2024-03-18 16:54 UTC, thealmarty commented
I changed the constraint with the latest commit. It doesn't fail with `cargo test` and the compiler tests. Please review.

2024-03-18 18:15 UTC, morganthomas approved these changes

2024-03-18 18:15 UTC, merged